// This file is auto-generated by @hey-api/openapi-ts

/**
 * AWSCloudScanRequest
 * AWS Cloud Scan Request with encrypted credentials
 */
export type AwsCloudScanRequest = {
    /**
     * Encrypted Aws Access Key
     */
    encrypted_aws_access_key: string;
    /**
     * Encrypted Aws Secret Key
     */
    encrypted_aws_secret_key: string;
    /**
     * Encrypted Aws Session Token
     */
    encrypted_aws_session_token?: string | null;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Excluded Regions
     */
    excluded_regions?: Array<string> | null;
    /**
     * Scan Options
     */
    scan_options?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RegionResponse
 * Region response model
 */
export type RegionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Cloud Provider
     */
    cloud_provider: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
};

/**
 * ScanListRequest
 */
export type ScanListRequest = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Cloud Provider
     */
    cloud_provider?: string | null;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
};

/**
 * ScanListResponse
 * Scan list response model
 */
export type ScanListResponse = {
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Status
     */
    status: string | null;
    /**
     * Cloud Provider
     */
    cloud_provider: string | null;
    /**
     * Created By
     */
    created_by: string | null;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
};

/**
 * ScanResponse
 * Scan response model
 */
export type ScanResponse = {
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Message
     */
    message: string;
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * ServiceScanRequest
 */
export type ServiceScanRequest = {
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Region
     */
    region?: string | null;
};

/**
 * ServiceScanResponse
 * Service scan result response model
 */
export type ServiceScanResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Service Name
     */
    service_name: string | null;
    /**
     * Region
     */
    region: string | null;
    /**
     * Scan Result Metadata
     */
    scan_result_metadata: {
        [key: string]: unknown;
    } | null;
    /**
     * Service Scan Data
     */
    service_scan_data: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Tenant Id
     */
    tenant_id: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AwsCloudScanApiScanAwsCloudScanPostData = {
    body: AwsCloudScanRequest;
    path?: never;
    query?: never;
    url: '/api/scan/aws-cloud-scan';
};

export type AwsCloudScanApiScanAwsCloudScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AwsCloudScanApiScanAwsCloudScanPostError = AwsCloudScanApiScanAwsCloudScanPostErrors[keyof AwsCloudScanApiScanAwsCloudScanPostErrors];

export type AwsCloudScanApiScanAwsCloudScanPostResponses = {
    /**
     * Successful Response
     */
    200: ScanResponse;
};

export type AwsCloudScanApiScanAwsCloudScanPostResponse = AwsCloudScanApiScanAwsCloudScanPostResponses[keyof AwsCloudScanApiScanAwsCloudScanPostResponses];

export type GetServiceScanResultApiScanServiceScanResultPostData = {
    body: ServiceScanRequest;
    path?: never;
    query?: never;
    url: '/api/scan/service-scan-result';
};

export type GetServiceScanResultApiScanServiceScanResultPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServiceScanResultApiScanServiceScanResultPostError = GetServiceScanResultApiScanServiceScanResultPostErrors[keyof GetServiceScanResultApiScanServiceScanResultPostErrors];

export type GetServiceScanResultApiScanServiceScanResultPostResponses = {
    /**
     * Successful Response
     */
    200: ServiceScanResponse;
};

export type GetServiceScanResultApiScanServiceScanResultPostResponse = GetServiceScanResultApiScanServiceScanResultPostResponses[keyof GetServiceScanResultApiScanServiceScanResultPostResponses];

export type GetScansApiScanScansPostData = {
    body: ScanListRequest;
    path?: never;
    query?: never;
    url: '/api/scan/scans';
};

export type GetScansApiScanScansPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScansApiScanScansPostError = GetScansApiScanScansPostErrors[keyof GetScansApiScanScansPostErrors];

export type GetScansApiScanScansPostResponses = {
    /**
     * Response Get Scans Api Scan Scans Post
     * Successful Response
     */
    200: Array<ScanListResponse>;
};

export type GetScansApiScanScansPostResponse = GetScansApiScanScansPostResponses[keyof GetScansApiScanScansPostResponses];

export type GetScanStatusApiScanScanStatusScanIdGetData = {
    body?: never;
    path: {
        /**
         * Scan Id
         */
        scan_id: string;
    };
    query?: never;
    url: '/api/scan/scan-status/{scan_id}';
};

export type GetScanStatusApiScanScanStatusScanIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanStatusApiScanScanStatusScanIdGetError = GetScanStatusApiScanScanStatusScanIdGetErrors[keyof GetScanStatusApiScanScanStatusScanIdGetErrors];

export type GetScanStatusApiScanScanStatusScanIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetScanApiScanScanScanIdGetData = {
    body?: never;
    path: {
        /**
         * Scan Id
         */
        scan_id: string;
    };
    query?: never;
    url: '/api/scan/scan/{scan_id}';
};

export type GetScanApiScanScanScanIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanApiScanScanScanIdGetError = GetScanApiScanScanScanIdGetErrors[keyof GetScanApiScanScanScanIdGetErrors];

export type GetScanApiScanScanScanIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRegionsApiRegionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cloud Provider
         * Filter by cloud provider (AWS, GCP, AZURE, etc.)
         */
        cloud_provider?: string | null;
    };
    url: '/api/regions/';
};

export type GetRegionsApiRegionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegionsApiRegionsGetError = GetRegionsApiRegionsGetErrors[keyof GetRegionsApiRegionsGetErrors];

export type GetRegionsApiRegionsGetResponses = {
    /**
     * Response Get Regions Api Regions  Get
     * Successful Response
     */
    200: Array<RegionResponse>;
};

export type GetRegionsApiRegionsGetResponse = GetRegionsApiRegionsGetResponses[keyof GetRegionsApiRegionsGetResponses];

export type GetRegionsByProviderApiRegionsCloudProviderGetData = {
    body?: never;
    path: {
        /**
         * Cloud Provider
         */
        cloud_provider: string;
    };
    query?: never;
    url: '/api/regions/{cloud_provider}';
};

export type GetRegionsByProviderApiRegionsCloudProviderGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegionsByProviderApiRegionsCloudProviderGetError = GetRegionsByProviderApiRegionsCloudProviderGetErrors[keyof GetRegionsByProviderApiRegionsCloudProviderGetErrors];

export type GetRegionsByProviderApiRegionsCloudProviderGetResponses = {
    /**
     * Response Get Regions By Provider Api Regions  Cloud Provider  Get
     * Successful Response
     */
    200: Array<RegionResponse>;
};

export type GetRegionsByProviderApiRegionsCloudProviderGetResponse = GetRegionsByProviderApiRegionsCloudProviderGetResponses[keyof GetRegionsByProviderApiRegionsCloudProviderGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConfigApiConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigApiConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};